name = "membership-nft/onchain"
version = "0.0.1"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Membership NFT Minting Smart Contracts"

[repository]
user = "membership-nft"
project = "onchain"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.23"
source = "github"

[config]
